spring:
  application:
    name: trakr
  datasource:
    url: jdbc:postgresql://localhost:5433/trakr
    username: trakr-user
    password: securepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

jwt:
  secret: cFA5v7CmIv1Z1N1wCuLxV/woQ0z9quBuf5MknivXaIU=
