spring:
  application:
    name: trakr
  datasource:
    url: jdbc:postgresql://localhost:5433/trakr
    username: trakr-user
    password: securepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
